// <auto-generated />
namespace Sunvalley_PLSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reportedMovement_listo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reportedMovement_listo));
        
        string IMigrationMetadata.Id
        {
            get { return "201606291816041_reportedMovement_listo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
