// <auto-generated />
namespace Sunvalley_PLSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_table_ReportedMovements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_table_ReportedMovements));
        
        string IMigrationMetadata.Id
        {
            get { return "201606282014118_added_table_ReportedMovements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
