// <auto-generated />
namespace Sunvalley_PLSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class house_changedAttr_postalCodeToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(house_changedAttr_postalCodeToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201604291951501_house_changedAttr_postalCodeToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
